import { BlogPost } from "../blogs";

export const BLOGS_PART_225: BlogPost[] = [
    {
        slug: "tunguska-event-meteor",
        title: "The Sky Split in Two: The Tunguska Event",
        description: "In 1908, a massive explosion flattened 80 million trees in Siberia. There was no crater. What happened?",
        category: "Physics",
        publishedAt: "2027-01-05",
        imageUrl: "/images/tunguska-trees.png",
        tags: ["Physics", "Space", "Disaster"],
        content: `
## Introduction: 7:17 AM
June 30, 1908. Siberia.
A fireball brighter than the sun.
A shockwave that circled the Earth twice.
It knocked people down 40 miles away.
It flattened 2,000 square kilometers of forest.
But when expeditions arrived... No crater.
Just trees knocked down in a butterfly pattern.

## 1. The Airburst
For decades, it was a mystery. Aliens? Antimatter? Black Hole?
Now we know vast.
It was a stony meteor (50m wide).
It entered the atmosphere at 33,000 mph.
The pressure was so high it exploded *in the air* (5 miles up).
An **Airburst**.
It delivered the energy of 1,000 Hiroshimas without hitting the ground.

## 2. City Killer
If it had hit London, London would be gone.
It happens every few hundred years.
Chelyabinsk (2013) was a smaller version.
We are sitting ducks in a cosmic shooting gallery.

> **One-Minute Summary**
>
> The **Tunguska Event** was a massive explosion that occurred near the Podkamennaya Tunguska River in Russia in 1908. It is attributed to the **Airburst** of a meteoroid or comet fragment. Because it exploded in the atmosphere, it left no impact crater but flattened 80 million trees. It remains the largest impact event on Earth in recorded history.
        `,
    },
    {
        slug: "fukushima-nuclear-disaster",
        title: "The Tsunami and the Meltdown: Fukushima",
        description: "Chernobyl was human error. Fukushima was nature. A 9.0 earthquake, a 14-meter wave, and 3 nuclear meltdowns.",
        category: "Physics",
        publishedAt: "2027-01-06",
        imageUrl: "/images/fukushima-plant.png",
        tags: ["Physics", "Nuclear", "Disaster"],
        content: `
## Introduction: The Wall
Japan built a sea wall to stop tsunamis. It was 10 meters high.
On March 11, 2011, the Tsunami was 14 meters high.
The water flooded the basement.
The basement had the backup diesel generators.
The power died. The cooling pumps stopped.

## 1. The Meltdown
Nuclear fuel is hot. Even if you turn the reactor off, it is hot.
Without water circulation, it boils the water away.
Then the fuel melts (Corium).
The Zirconium cladding reacts with steam to create **Hydrogen Gas**.
BOOM.
Reactors 1, 2, and 3 exploded.

## 2. The Legacy
It wasn't as bad as Chernobyl (containment vessels mostly held).
But it killed Nuclear Power in Japan (and Germany).
We are still pumping radioactive water into the ocean (Tritium).
Robots sent inside the core die instantly from radiation.
It will take 40 years to clean up.

> **One-Minute Summary**
>
> The **Fukushima Daiichi Nuclear Disaster** was a 2011 energy accident initiated by the Tōhoku earthquake and tsunami. The flood disabled the emergency generators required to cool the reactors, leading to three **Nuclear Meltdowns**, hydrogen explosions, and the release of radioactive contamination. It is the only other event besides Chernobyl to be classified as Level 7 on the INES scale.
        `,
    },
    {
        slug: "geomagnetic-reversal-pole-flip-v2",
        title: "When North Becomes South: Geomagnetic Reversal",
        description: "Your compass points North. But in the past, it pointed South. We are overdue for a flip. What happens to our electronics?",
        category: "Physics",
        publishedAt: "2027-01-07",
        imageUrl: "/images/magnetic-pole-flip.png",
        tags: ["Physics", "Earth", "Magnetism"],
        content: `
## Introduction: The Shield
Earth has a magnetic field generated by swirling liquid iron in the core.
This shield protects us from Solar Winds.
But the shield isn't stable.
Every 450,000 years (on average), the poles flip.
North becomes South. South becomes North.
The last one was 780,000 years ago. We are late.

## 1. The Signs
The Magnetic North Pole is sprinting towards Siberia (50km/year).
The "South Atlantic Anomaly" (a weak spot in the field) is growing.
Satellites passing over it often glitch.

## 2. The Danger
It's not the flip itself; it's the transition.
During the flip, the shield weakens to 10%.
Solar radiation gets through.
Cancer rates go up.
But the real victim is the Grid.
A weak shield means a Solar Storm could fry every transformer on Earth.
No GPS. No Internet. No Power.

> **One-Minute Summary**
>
> A **Geomagnetic Reversal** is a change in a planet's magnetic field such that the positions of magnetic north and magnetic south are interchanged. The Earth's field has alternated between periods of normal and reversed polarity throughout history. During a reversal, the protective magnetosphere weakens, exposing the planet to increased cosmic and solar radiation.
        `,
    },
    {
        slug: "rogue-black-holes-wandering",
        title: "The Invisible Predator: Rogue Black Holes",
        description: "Most Black Holes sit in the center of galaxies. But some were kicked out. They are invisible, silent, and moving at 1,000 miles per second.",
        category: "Physics",
        publishedAt: "2027-01-08",
        imageUrl: "/images/rogue-black-hole.png",
        tags: ["Physics", "Space", "Scary"],
        content: `
## Introduction: The Ejection
When two galaxies collide, their Black Holes merge.
But sometimes, due to gravitational waves ("The Kick"), one is shot out into deep space.
It becomes a **Rogue Black Hole**.
It wanders the void, alone.

## 1. Detection
Since it has no star to eat, it has no accretion disk.
It is perfectly black. Invisible.
We only see it if it passes *in front* of a star (Microlensing).
Gravity bends the light.

## 2. The Scenario
If one entered our Solar System...
We wouldn't see it until the planets started wobbling.
It would eat the Earth. Or worse, fling Earth out of the Solar System into the freezing dark.
Statistically unlikely? Yes.
Impossible? No.

> **One-Minute Summary**
>
> A **Rogue Black Hole** is an intergalactic black hole that is not gravitationally bound to any galaxy. Often ejected during galaxy mergers, they travel through space at high velocities. Because they are not consuming matter, they emit no light and are detectable only through **Gravitational Lensing**. There may be millions of them wandering the Milky Way unnoticed.
        `,
    },
    {
        slug: "big-rip-end-of-universe",
        title: "The Ultimate Shredder: The Big Rip",
        description: "Dark Energy is pushing the universe apart. If it gets stronger, it won't just separate galaxies. It will tear atoms apart.",
        category: "Physics",
        publishedAt: "2027-01-09",
        imageUrl: "/images/big-rip.png",
        tags: ["Physics", "Cosmology", "End of World"],
        content: `
## Introduction: Phantom Energy
We know the universe is expanding (Dark Energy).
If Dark Energy is constant (Cosmological Constant), we get **Heat Death** (Cold and lonely).
But what if Dark Energy gets *stronger* over time?
This is **Phantom Energy**.

## 1. The Timeline
First, Galaxies are torn apart (Milky Way scatters).
Then, Solar Systems are torn apart (Earth leaves Sun).
Then, Planets explode.
Then, Molecules.
Then, Atoms.
Finally, the fabric of Spacetime itself is ripped.

## 2. The End
At the final singularity, the distance between any two points becomes infinite instantly.
Physics ends.
It is the most violent end to the universe possible.
Sleep tight.

> **One-Minute Summary**
>
> **The Big Rip** is a hypothetical cosmological model concerning the ultimate fate of the universe. It relies on the concept of **Phantom Energy** (Dark Energy increasing over time). If true, the expansion of the universe will eventually become so powerful that it overcomes all forces—gravity, electromagnetic, and nuclear—tearing apart galaxies, stars, planets, and finally atoms themselves.
        `,
    },
];
